package Tables;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import javafx.event.ActionEvent;

public class Test {
	@FXML
	private Button CreateNewOrderBtn;
	@FXML
	private TextField CreateOrderIdText;
	@FXML
	private TextField CreateTableNumberText;
	@FXML
	private TextField CreateDishText;
	@FXML
	private TextField CreatePriceText;
	@FXML
	private TextField CreateCommentText;

	// Event Listener on Button[#CreateNewOrderBtn].onAction
	@FXML
	public void createNewOrder(ActionEvent event) {
		// TODO Autogenerated
	}
}
